/* ═══════════════════════════════════════════════════════════════════════
   CLARK · OpenOrdersTransferModal (Phase 2 — V21.21.65)
   ───────────────────────────────────────────────────────────────────────
   ترحيل الأوامر المفتوحة من الموسم الجاري إقفاله للموسم الجديد.

   الدلالة (مؤكَّدة من Ahmed):
   ─────────────────────────
   • **MOVE كامل مش COPY**: لكل أمر مختار → كتابة في seasons/{to}/orders/{docId}
     مع season=to + حذف من seasons/{from}/orders/{docId}، **ذرّياً** في نفس
     writeBatch. نفس الـ id والـ docId → لا ازدواج، idempotent (إعادة التشغيل
     بتلاقي الأمر مش موجود في القديم فبتتخطّاه).
   • القيود المحاسبية/الخزنة/الدفعات **مابتتحركش** — متخزّنة منفصلة بالتاريخ
     (accountingDays/treasuryDays/custPayments) فبتفضل صح في مكانها.

   الأمان (مؤكَّد):
   ─────────────────
   • **نسخة احتياطية شاملة إجبارية** (createComprehensiveBackup) قبل أي كتابة.
   • تأكيد صريح + معاينة العدد + overlay قافل للشاشة أثناء التنفيذ.
   • batch لكل ≤200 أمر (set+delete = 2 ops/أمر، أقل من حد 500/commit).

   التوقيت: لازم يشتغل والموسم القديم **لسه نشط** (عشان data.orders محمّلة منه)؛
   بيكتب في مجموعة الموسم الجديد ويحذف من الحالي. بعد الترحيل تفعّل الجديد.
   ═══════════════════════════════════════════════════════════════════════ */

import { useState, useMemo } from "react";
import { Btn } from "../ui.jsx";
import { doc, writeBatch } from "firebase/firestore";
import { db } from "../../firebase.js";
import { buildOpenOrders } from "../../utils/accounting/seasonClosing.js";
import { createComprehensiveBackup } from "../../utils/comprehensiveBackup.js";
import { fmt } from "../../utils/format.js";
import { ask, tell } from "../../utils/popups.js";

const CHUNK = 200; /* أوامر/batch — كل أمر set+delete = 2 ops، آمن تحت حد 500 */

export function OpenOrdersTransferModal({ data, fromSeason, toSeason, T, FS, isMob, onClose, userName, showToast, upConfig }){
  const d = data || {};
  const open = useMemo(() => buildOpenOrders(d), [d]);
  const [selected, setSelected] = useState(() => new Set(open.map(o => o.id)));
  const [busy, setBusy] = useState(false);
  const [progress, setProgress] = useState({ n: 0, total: 0, label: "" });

  const toggle = (id) => setSelected(p => { const n = new Set(p); if(n.has(id)) n.delete(id); else n.add(id); return n; });
  const allChecked = open.length > 0 && selected.size === open.length;
  const toggleAll = () => setSelected(allChecked ? new Set() : new Set(open.map(o => o.id)));

  const doTransfer = async () => {
    if(busy) return;
    const from = (fromSeason || "").trim();
    const to = (toSeason || "").trim();
    if(!to){ await tell("الموسم الجديد مطلوب", "حدد اسم الموسم الجديد أولاً (من قسم «فتح الموسم الجديد»)", { danger: true }); return; }
    if(to === from){ await tell("نفس الموسم", "الموسم الجديد لازم يكون مختلف عن الموسم الحالي", { danger: true }); return; }
    const picked = open.filter(o => selected.has(o.id) && o.id);
    if(picked.length === 0){ await tell("لا شيء محدد", "اختر أمر واحد على الأقل للترحيل", { danger: true }); return; }

    const ok = await ask(
      "ترحيل الأوامر المفتوحة",
      `هيتم نقل ${picked.length} أمر من «${from}» لـ «${to}» (نقل كامل — مش نسخ).\n\n` +
      `⚠️ قبل النقل هتتعمل نسخة احتياطية شاملة إجبارية (كل المواسم والبيانات).\n` +
      `العملية ذرّية وقابلة للتكرار. الأوامر القديمة بتفضل في موسمها لو ما اخترتهاش.\n\nمتأكد تكمل؟`,
      { confirmText: "نسخة احتياطية وترحيل", danger: true }
    );
    if(!ok) return;

    setBusy(true);
    try {
      /* 1) نسخة احتياطية شاملة إجبارية */
      setProgress({ n: 0, total: picked.length, label: "📦 جاري عمل نسخة احتياطية شاملة..." });
      const bk = await createComprehensiveBackup({
        label: `قبل ترحيل أوامر ${from}→${to}`,
        user: userName || "",
        autoGenerated: true,
        onProgress: (msg) => setProgress(p => ({ ...p, label: "📦 نسخة احتياطية: " + (typeof msg === "string" ? msg : "...") })),
      });

      /* 2) النقل الذرّي على دفعات */
      const byId = new Map((d.orders || []).map(o => [o.id, o])); /* O(1) lookup */
      let done = 0;
      for(let i = 0; i < picked.length; i += CHUNK){
        const slice = picked.slice(i, i + CHUNK);
        const batch = writeBatch(db);
        let inBatch = 0;
        slice.forEach(o => {
          const orderData = byId.get(o.id);
          if(!orderData || !orderData._docId) return; /* تخطَّ اللي مالهوش docId */
          const clean = { ...orderData, season: to };
          delete clean._docId;
          batch.set(doc(db, "seasons", to, "orders", orderData._docId), clean);
          batch.delete(doc(db, "seasons", from, "orders", orderData._docId));
          inBatch++;
        });
        if(inBatch > 0) await batch.commit();
        done += slice.length;
        setProgress({ n: done, total: picked.length, label: `🚚 ترحيل ${done}/${picked.length}...` });
      }

      /* 3) سجّل الموسم الجديد في القائمة (من غير تفعيل — التفعيل خطوة منفصلة) */
      if(typeof upConfig === "function"){
        upConfig(cfg => {
          if(!Array.isArray(cfg.seasons)) cfg.seasons = [];
          if(!cfg.seasons.includes(to)) cfg.seasons.push(to);
        });
      }

      if(typeof showToast === "function") showToast(`✅ تم ترحيل ${picked.length} أمر لموسم «${to}» (نسخة احتياطية: ${bk?.backupId || "—"})`);
      onClose(true);
    } catch(e){
      console.error("[Phase2] transfer error:", e);
      await tell("فشل الترحيل", (e.message || String(e)) + "\n\nالبيانات لم تتغير جزئياً إن أمكن — راجع النسخة الاحتياطية.", { danger: true });
    } finally {
      setBusy(false);
    }
  };

  const prodCount = open.filter(o => o.status === "production").length;
  const stockCount = open.length - prodCount;

  return <div className="pop-overlay" style={{
    position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", zIndex: 10002,
    display: "flex", alignItems: "center", justifyContent: "center", padding: isMob ? 4 : 16,
  }} onClick={busy ? undefined : () => onClose(false)}>
    <div onClick={e => e.stopPropagation()} style={{
      background: T.cardSolid, borderRadius: 14, width: "100%", maxWidth: 720,
      maxHeight: "94vh", display: "flex", flexDirection: "column",
      border: "1px solid " + T.brd, boxShadow: "0 25px 70px rgba(0,0,0,0.4)",
    }}>
      {/* Header */}
      <div style={{ padding: isMob ? "12px 14px" : "14px 18px", borderBottom: "1px solid " + T.brd, display: "flex", justifyContent: "space-between", alignItems: "center", flexShrink: 0 }}>
        <div>
          <div style={{ fontSize: FS + 2, fontWeight: 800, color: T.warn }}>🚚 ترحيل الأوامر المفتوحة</div>
          <div style={{ fontSize: FS - 2, color: T.textSec, marginTop: 2 }}>
            من «{fromSeason || "—"}» <span style={{ color: T.warn }}>→</span> «{toSeason || "—"}» · نقل كامل (مش نسخ)
          </div>
        </div>
        {!busy && <Btn ghost small onClick={() => onClose(false)}>✕</Btn>}
      </div>

      {/* Summary bar */}
      <div style={{ padding: isMob ? "10px 14px" : "12px 18px", background: T.bg, borderBottom: "1px solid " + T.brd, flexShrink: 0, display: "flex", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
        <div style={{ fontSize: FS - 2, color: T.textSec }}>
          أوامر مفتوحة: <b style={{ color: T.text }}>{open.length}</b>
          {prodCount > 0 && <span> · تحت التنفيذ: <b style={{ color: T.warn }}>{prodCount}</b></span>}
          {stockCount > 0 && <span> · مخزون جاهز: <b style={{ color: T.accent }}>{stockCount}</b></span>}
        </div>
        <div style={{ flex: 1 }} />
        {open.length > 0 && <Btn ghost small onClick={toggleAll} disabled={busy}>{allChecked ? "☐ إلغاء الكل" : "☑ تحديد الكل"}</Btn>}
        <span style={{ fontSize: FS - 2, fontWeight: 800, color: T.warn }}>محدد: {selected.size}</span>
      </div>

      {/* Body — list */}
      <div style={{ flex: 1, overflowY: "auto", padding: isMob ? 12 : 16 }}>
        {open.length === 0
          ? <div style={{ padding: 30, textAlign: "center", color: T.textMut, background: T.bg, borderRadius: 8, border: "1px dashed " + T.brd }}>
              ✓ لا توجد أوامر مفتوحة في «{fromSeason}» — مفيش حاجة تترحّل
            </div>
          : <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {open.map(o => {
                const on = selected.has(o.id);
                return <div key={o.id} onClick={() => !busy && toggle(o.id)} style={{
                  display: "flex", alignItems: "center", gap: 10, padding: "9px 12px", borderRadius: 8, cursor: busy ? "default" : "pointer",
                  background: on ? T.accent + "08" : T.cardSolid, border: "1px solid " + (on ? T.accent + "50" : T.brd),
                }}>
                  <span style={{ fontSize: 20, color: on ? T.accent : T.textMut, fontWeight: 800 }}>{on ? "☑" : "☐"}</span>
                  <span style={{ fontSize: FS - 3, fontWeight: 800, color: o.status === "production" ? T.warn : T.accent, padding: "2px 7px", background: (o.status === "production" ? T.warn : T.accent) + "15", borderRadius: 5, whiteSpace: "nowrap" }}>
                    {o.status === "production" ? "تحت التنفيذ" : "مخزون"}
                  </span>
                  <span style={{ flex: 1, fontSize: FS - 1, fontWeight: 600, color: T.text, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {o.modelNo}{o.modelDesc ? " — " + o.modelDesc : ""}{o.customer ? " · " + o.customer : ""}
                  </span>
                  <span style={{ fontSize: FS - 3, color: T.textSec, whiteSpace: "nowrap", fontFamily: "monospace", direction: "ltr" }}>
                    مقصوص {fmt(o.ordered)} · متاح {fmt(o.avail)}
                  </span>
                </div>;
              })}
            </div>}
      </div>

      {/* Footer */}
      <div style={{ padding: isMob ? 12 : 14, background: T.bg, borderTop: "1px solid " + T.brd, display: "flex", gap: 8, justifyContent: "space-between", alignItems: "center", flexShrink: 0 }}>
        <div style={{ fontSize: FS - 3, color: T.textMut, lineHeight: 1.5, maxWidth: "60%" }}>
          🛡️ نسخة احتياطية شاملة إجبارية قبل النقل · العملية ذرّية وقابلة للتكرار
        </div>
        <Btn primary onClick={doTransfer} disabled={busy || selected.size === 0 || open.length === 0} style={{ background: T.warn, color: "#fff", border: "none", fontWeight: 800, padding: "10px 22px" }}>
          {busy ? "⏳ جاري..." : `🚚 ترحيل ${selected.size} أمر`}
        </Btn>
      </div>
    </div>

    {/* Busy overlay (locks the screen during transfer) */}
    {busy && <div style={{ position: "fixed", inset: 0, zIndex: 10003, background: "rgba(0,0,0,0.55)", backdropFilter: "blur(3px)", display: "flex", alignItems: "center", justifyContent: "center", padding: 16 }} onClick={e => e.stopPropagation()}>
      <div style={{ background: T.cardSolid, borderRadius: 18, padding: isMob ? "20px 18px" : "28px 32px", width: "100%", maxWidth: 460, boxShadow: "0 24px 80px rgba(0,0,0,0.4)", border: "1px solid " + T.brd }}>
        <div style={{ fontSize: FS + 2, fontWeight: 800, color: T.text, marginBottom: 6 }}>🚚 جاري ترحيل الأوامر</div>
        <div style={{ fontSize: FS - 1, color: T.textSec, fontWeight: 700, marginBottom: 10, display: "flex", justifyContent: "space-between" }}>
          <span>{progress.label || "تجهيز..."}</span>
          {progress.total > 0 && <span style={{ fontFamily: "monospace", color: T.warn }}>{progress.n}/{progress.total}</span>}
        </div>
        <div style={{ height: 12, background: T.bg, borderRadius: 8, overflow: "hidden", border: "1px solid " + T.brd, marginBottom: 12 }}>
          <div style={{ height: "100%", width: progress.total > 0 ? (progress.n / progress.total * 100) + "%" : "30%", background: "linear-gradient(90deg," + T.warn + "," + T.warn + "DD)", transition: "width 0.3s" }} />
        </div>
        <div style={{ padding: "8px 12px", background: T.warn + "08", border: "1px solid " + T.warn + "30", borderRadius: 8, fontSize: FS - 2, color: T.warn, lineHeight: 1.6 }}>
          ⚠️ لا تغلق التطبيق — العملية بتعمل نسخة احتياطية ثم تنقل الأوامر ذرّياً
        </div>
      </div>
    </div>}
  </div>;
}
