/* ═══════════════════════════════════════════════════════════════
   CLARK — POST /api/admin/migration-log (V21.9.28)
   ───────────────────────────────────────────────────────────────
   Returns recent migrationLog entries + linked backups so the
   admin can see exactly what each diagnostic button did, and
   restore from a backup if needed.

   Actions:
     • action="list" — returns last N entries sorted by .at desc
       Body: { limit?: 50, sinceISO?: "2026-05-11T00:00:00Z",
               filterType?: "fix-flags-v21.9.24" }
     • action="get_backup" — returns the contents of a backup doc
       Body: { backup_doc_id }
     • action="restore_backup" — restores cfg fields from a backup
       Body: { backup_doc_id, fields_to_restore: ["shopifyCustomers", ...] }

   The "restore" action writes the saved cfg.<field> arrays BACK to
   factory/config. It does NOT touch partitioned collections —
   use /api/maintenance/recover-legacy-data for that.

   Auth: admin Bearer
   ═══════════════════════════════════════════════════════════════ */

import { getDb, setCors, verifyAdminToken } from "../_firebase.js";

const PRODUCTS_COL = "shopifyProductsDocs";

/* V21.9.29 — restore products backup to shopifyProductsDocs (not cfg).
   Also removes the restored IDs from the deletedProductIds blacklist so
   the products aren't filtered out by future syncs. */
async function restoreProductsBackup(res, auth, backupDocId, backup) {
  const db = getDb();
  const products = Array.isArray(backup.shopifyProducts) ? backup.shopifyProducts : [];
  if (products.length === 0) {
    return res.status(400).json({ ok: false, error: "الـ backup مفهوش products" });
  }

  /* Pre-restore safety: snapshot current state */
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const preRestoreId = "pre-restore-products-from-" + backupDocId.slice(0, 30) + "-v21.9.29-" + ts;
  const cfgSnap = await db.collection("factory").doc("config").get();
  const cfgBefore = cfgSnap.exists ? (cfgSnap.data() || {}) : {};
  const blacklistBefore = Array.isArray(cfgBefore.shopifyConfig?.deletedProductIds)
    ? cfgBefore.shopifyConfig.deletedProductIds : [];
  /* Read current partitioned state for full backup */
  const existing = [];
  const exSnap = await db.collection(PRODUCTS_COL).get();
  exSnap.forEach(d => { const data = d.data(); if (data) existing.push(data); });
  await db.collection("backups").doc(preRestoreId).set({
    label: "Snapshot قبل restore-products من " + backupDocId,
    autoGenerated: true,
    migrationType: "pre-restore-products-v21.9.29",
    createdAt: new Date().toISOString(),
    createdBy: auth.email || auth.uid,
    restored_from: backupDocId,
    shopifyProducts: existing,
    blacklist_before: blacklistBefore,
  });

  /* Write products to shopifyProductsDocs (batch) */
  let written = 0;
  const BATCH = 400;
  for (let i = 0; i < products.length; i += BATCH) {
    const batch = db.batch();
    for (const p of products.slice(i, i + BATCH)) {
      const id = p.id || p.shopify_id;
      if (!id) continue;
      const safeId = String(id).replace(/\//g, "_");
      batch.set(db.collection(PRODUCTS_COL).doc(safeId), { ...p, id: safeId });
      written++;
    }
    await batch.commit();
  }

  /* Remove restored IDs from the deletedProductIds blacklist (so future
     syncs don't skip them again). */
  const restoredIds = new Set(products.map(p => String(p.id || p.shopify_id)).filter(Boolean));
  const newBlacklist = blacklistBefore.filter(id => !restoredIds.has(String(id)));
  await db.collection("factory").doc("config").set({
    shopifyConfig: {
      ...(cfgBefore.shopifyConfig || {}),
      deletedProductIds: newBlacklist,
      last_restore_products_at: new Date().toISOString(),
      last_restore_products_by: auth.email || auth.uid,
      last_restore_products_from: backupDocId,
    },
  }, { merge: true });

  /* Audit log */
  try {
    await db.collection("migrationLog").doc("restore-products-from-backup-v21.9.29-" + Date.now()).set({
      type: "restore-products-from-backup-v21.9.29",
      status: "success",
      restored_from: backupDocId,
      products_restored: written,
      blacklist_cleared: blacklistBefore.length - newBlacklist.length,
      pre_restore_backup_id: preRestoreId,
      by: auth.email || auth.uid,
      at: new Date().toISOString(),
    });
  } catch (_) {}

  return res.status(200).json({
    ok: true,
    products_restored: written,
    blacklist_cleared: blacklistBefore.length - newBlacklist.length,
    backup_doc_id: backupDocId,
    pre_restore_backup_id: preRestoreId,
    fields_count: 1,
    restored: { shopifyProducts: written },
    message: "✅ تم! استرجعنا " + written + " منتج إلى shopifyProductsDocs + شيلنا " + (blacklistBefore.length - newBlacklist.length) + " ID من الـ blacklist.",
  });
}

export default async function handler(req, res) {
  setCors(res, req);
  if (req.method === "OPTIONS") { res.status(204).end(); return; }
  if (req.method !== "POST") {
    return res.status(405).json({ ok: false, error: "POST فقط" });
  }
  const auth = await verifyAdminToken(req.headers.authorization);
  if (!auth.ok) {
    return res.status(auth.status).json({ ok: false, error: auth.error });
  }

  const body = (typeof req.body === "string") ? JSON.parse(req.body || "{}") : (req.body || {});
  const action = String(body.action || "list").trim();

  try {
    if (action === "list") return handleList(res, body);
    if (action === "get_backup") return handleGetBackup(res, body);
    if (action === "restore_backup") return handleRestoreBackup(res, auth, body);
    return res.status(400).json({ ok: false, error: "action غير معروف" });
  } catch (e) {
    console.error("[V21.9.28 migration-log] failed:", e);
    return res.status(500).json({ ok: false, error: e.message });
  }
}

async function handleList(res, body) {
  const db = getDb();
  const limit = Math.max(1, Math.min(200, Number(body.limit) || 50));
  const sinceISO = body.sinceISO ? String(body.sinceISO) : null;
  const filterType = body.filterType ? String(body.filterType) : null;

  let query = db.collection("migrationLog").orderBy("at", "desc").limit(limit);
  /* Firestore doesn't support OR/contains queries on free-text well.
     We'll filter client-side after fetching. */

  const snap = await query.get();
  const entries = [];
  snap.forEach(d => {
    const data = d.data() || {};
    if (sinceISO && data.at && data.at < sinceISO) return;
    if (filterType && !(data.type || "").includes(filterType)) return;
    entries.push({
      id: d.id,
      type: data.type || "",
      status: data.status || "",
      at: data.at || "",
      by: data.by || "",
      backup_doc_id: data.backup_doc_id || null,
      /* Surface the most-useful summary fields per type */
      flags_set: data.flags_set || data.flagsSet || null,
      fields_stripped: data.fields_stripped || data.fieldsStripped || null,
      detected: data.detected || null,
      warnings: data.warnings || null,
      items_migrated: data.items_migrated || data.items_written || data.items_restored ||
                      data.entries_removed || data.applied || null,
      orders_migrated: data.orders_migrated || null,
      days_count: data.days_count || null,
      /* Generic dump of everything else for the modal */
      raw: data,
    });
  });

  return res.status(200).json({
    ok: true,
    entries,
    total: entries.length,
    sinceISO,
    filterType,
  });
}

async function handleGetBackup(res, body) {
  const id = String(body.backup_doc_id || "").trim();
  if (!id) return res.status(400).json({ ok: false, error: "backup_doc_id مطلوب" });
  const db = getDb();
  const snap = await db.collection("backups").doc(id).get();
  if (!snap.exists) return res.status(404).json({ ok: false, error: "Backup مش موجود" });
  const data = snap.data() || {};
  /* Return summary + counts (don't ship full arrays unless needed) */
  const summary = {
    id: snap.id,
    label: data.label || "",
    migrationType: data.migrationType || "",
    createdAt: data.createdAt || "",
    createdBy: data.createdBy || "",
    contents: {},
  };
  /* Detect what arrays/objects the backup contains */
  for (const [key, val] of Object.entries(data)) {
    if (["label", "migrationType", "createdAt", "createdBy", "autoGenerated"].includes(key)) continue;
    if (Array.isArray(val)) {
      summary.contents[key] = { type: "array", count: val.length };
    } else if (val && typeof val === "object") {
      summary.contents[key] = { type: "object", keys: Object.keys(val).length };
    } else {
      summary.contents[key] = { type: typeof val, value: val };
    }
  }
  return res.status(200).json({ ok: true, backup: summary });
}

async function handleRestoreBackup(res, auth, body) {
  const id = String(body.backup_doc_id || "").trim();
  const fieldsToRestore = Array.isArray(body.fields_to_restore) ? body.fields_to_restore : null;
  if (!id) return res.status(400).json({ ok: false, error: "backup_doc_id مطلوب" });
  if (!fieldsToRestore || fieldsToRestore.length === 0) {
    return res.status(400).json({ ok: false, error: "fields_to_restore مطلوب (array)" });
  }

  const db = getDb();
  const backupSnap = await db.collection("backups").doc(id).get();
  if (!backupSnap.exists) return res.status(404).json({ ok: false, error: "Backup مش موجود" });
  const backup = backupSnap.data() || {};

  /* V21.9.29: smart routing — if the backup is from a bulk-products destructive
     action (delete_all / delete_from_clark), the data needs to go BACK to
     shopifyProductsDocs (not cfg). Same for customers if we ever add that. */
  const isProductsBackup = (backup.migrationType || "").includes("bulk-products-") &&
                          Array.isArray(backup.shopifyProducts);
  if (isProductsBackup && fieldsToRestore.includes("shopifyProducts")) {
    return restoreProductsBackup(res, auth, id, backup);
  }

  /* Validate: each requested field must exist in the backup */
  const missing = fieldsToRestore.filter(f => !(f in backup));
  if (missing.length > 0) {
    return res.status(400).json({
      ok: false,
      error: "Fields مش موجودة في الـ backup: " + missing.join(", "),
    });
  }

  /* Build the patch */
  const patch = {};
  const stats = {};
  for (const field of fieldsToRestore) {
    patch[field] = backup[field];
    if (Array.isArray(backup[field])) {
      stats[field] = backup[field].length;
    } else if (backup[field] && typeof backup[field] === "object") {
      stats[field] = Object.keys(backup[field]).length;
    } else {
      stats[field] = 1;
    }
  }

  /* Pre-restore backup of current state */
  const cfgRef = db.collection("factory").doc("config");
  const cfgSnap = await cfgRef.get();
  const cfg = cfgSnap.exists ? (cfgSnap.data() || {}) : {};
  const beforeSnapshot = {};
  for (const field of fieldsToRestore) beforeSnapshot[field] = cfg[field];

  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const newBackupId = "pre-restore-from-" + id.slice(0, 30) + "-v21.9.28-" + ts;
  await db.collection("backups").doc(newBackupId).set({
    label: "Backup قبل restore من " + id,
    autoGenerated: true,
    migrationType: "restore-backup-v21.9.28",
    createdAt: new Date().toISOString(),
    createdBy: auth.email || auth.uid,
    restored_from: id,
    fields_restored: fieldsToRestore,
    ...beforeSnapshot,
  });

  /* Apply the restore */
  await cfgRef.set(patch, { merge: true });

  /* Log */
  try {
    await db.collection("migrationLog").doc("restore-backup-v21.9.28-" + Date.now()).set({
      type: "restore-backup-v21.9.28",
      status: "success",
      restored_from: id,
      fields_restored: fieldsToRestore,
      stats,
      pre_restore_backup_id: newBackupId,
      by: auth.email || auth.uid,
      at: new Date().toISOString(),
    });
  } catch (_) {}

  return res.status(200).json({
    ok: true,
    restored: stats,
    fields_count: fieldsToRestore.length,
    backup_doc_id: id,
    pre_restore_backup_id: newBackupId,
    message: "✅ تم! استرجعنا " + fieldsToRestore.length + " field من backup.",
  });
}
