/* ═══════════════════════════════════════════════════════════════════════
   CLARK Accounting · Fixed Assets (V18.67)
   ───────────────────────────────────────────────────────────────────────
   CRUD layer for the `fixedAssets` Firestore collection.
   Each asset is a separate document — supports years of depreciation
   history per asset without bloating any single document.

   Schema (per document):
     id                       (auto-generated by Firestore)
     code                     "FA-2026-0001" (auto-numbered)
     name                     "ماكينة Juki 8500"
     category                 "ماكينات إنتاج" | "أثاث" | ... (free text)
     acquisitionDate          "YYYY-MM-DD"
     acquisitionCost          number (positive)
     salvageValue             number (>= 0)
     usefulLifeMonths         number (positive integer)
     depreciationMethod       "straight_line"  (V1: only this is supported)
     depreciationStartMonth   "YYYY-MM" — first month with depreciation charge
     depreciationEndMonth     "YYYY-MM" — last month with depreciation charge
     convention               "next-month" | "full-month"  (informational)

     ─── GL account codes (defaults editable per asset) ───
     assetAccountCode         e.g. "1410" — where the asset sits on BS
     accumDepAccountCode      e.g. "1490" — contra-asset for accumulated dep
     depExpenseAccountCode    e.g. "5410" — depreciation expense

     ─── Tracking ───
     status                   "active" | "disposed" | "fully_depreciated"
     lastDepreciatedThrough   "YYYY-MM" or null — last month fully depreciated
     totalDepreciated         number (cached sum, derived from journal)

     ─── Disposal ───
     disposalDate             "YYYY-MM-DD" or null
     disposalAmount           number (sale proceeds; 0 = scrapped)
     disposalNotes            string

     ─── Audit ───
     notes                    string
     createdAt, createdBy
     modifiedAt?, modifiedBy?
   ═══════════════════════════════════════════════════════════════════════ */

import { db } from "../../firebase.js";
import { collection, doc, addDoc, updateDoc, deleteDoc, getDoc, getDocs, onSnapshot, query, runTransaction } from "firebase/firestore";

const COLLECTION = "fixedAssets";

/* ─── Subscribe to all assets (live updates). Returns unsubscribe fn. ─── */
export function subscribeFixedAssets(onUpdate, onError){
  return onSnapshot(
    collection(db, COLLECTION),
    snap => {
      const list = snap.docs.map(d => ({ id: d.id, ...d.data() }));
      onUpdate(list);
    },
    err => {
      console.error("[fixedAssets] subscribe error:", err);
      if(typeof onError === "function") onError(err);
    }
  );
}

/* ─── One-shot fetch (for backfill or background tasks) ─── */
export async function fetchAllFixedAssets(){
  const snap = await getDocs(collection(db, COLLECTION));
  return snap.docs.map(d => ({ id: d.id, ...d.data() }));
}

/* ─── Get a single asset by id ─── */
export async function getFixedAsset(id){
  const ref = doc(db, COLLECTION, id);
  const snap = await getDoc(ref);
  if(!snap.exists()) return null;
  return { id: snap.id, ...snap.data() };
}

/* ─── Generate next asset code (sequential per year) ─── */
function _pad4(n){ return String(n).padStart(4, "0"); }
export function nextAssetCode(allAssets){
  const year = new Date().getFullYear();
  const prefix = `FA-${year}-`;
  let max = 0;
  (allAssets || []).forEach(a => {
    if(typeof a.code !== "string") return;
    if(!a.code.startsWith(prefix)) return;
    const tail = a.code.slice(prefix.length);
    const n = parseInt(tail, 10);
    if(Number.isInteger(n) && n > max) max = n;
  });
  return prefix + _pad4(max + 1);
}

/* ─── Compute depreciationStartMonth and depreciationEndMonth ─── */
function _pad2(n){ return String(n).padStart(2, "0"); }

/* Add `n` months to a "YYYY-MM" string. Returns new "YYYY-MM". */
function addMonths(ymStr, n){
  const [y, m] = ymStr.split("-").map(Number);
  /* total month index (0-based across years) */
  const total = y * 12 + (m - 1) + n;
  const ny = Math.floor(total / 12);
  const nm = (total % 12) + 1;
  return `${ny}-${_pad2(nm)}`;
}

export function computeDepreciationSchedule(acquisitionDate, usefulLifeMonths, convention){
  if(!acquisitionDate || !usefulLifeMonths) return { startMonth: null, endMonth: null };
  const d = new Date(acquisitionDate + "T00:00:00");
  const acqYM = `${d.getFullYear()}-${_pad2(d.getMonth() + 1)}`;
  let startMonth;
  if(convention === "full-month"){
    startMonth = acqYM;
  } else {
    /* next-month default */
    startMonth = addMonths(acqYM, 1);
  }
  /* End month = startMonth + usefulLifeMonths - 1 */
  const endMonth = addMonths(startMonth, Number(usefulLifeMonths) - 1);
  return { startMonth, endMonth };
}

/* ─── Create a new asset ─── */
export async function createFixedAsset(payload, allAssets, userName){
  const code = nextAssetCode(allAssets);
  const schedule = computeDepreciationSchedule(
    payload.acquisitionDate,
    payload.usefulLifeMonths,
    payload.convention || "next-month"
  );

  const docData = {
    code,
    name: payload.name || "",
    category: payload.category || "",
    acquisitionDate: payload.acquisitionDate,
    acquisitionCost: Number(payload.acquisitionCost) || 0,
    salvageValue: Number(payload.salvageValue) || 0,
    usefulLifeMonths: Number(payload.usefulLifeMonths) || 0,
    depreciationMethod: payload.depreciationMethod || "straight_line",
    depreciationStartMonth: schedule.startMonth,
    depreciationEndMonth: schedule.endMonth,
    convention: payload.convention || "next-month",
    assetAccountCode: payload.assetAccountCode || "1410",
    accumDepAccountCode: payload.accumDepAccountCode || "1490",
    depExpenseAccountCode: payload.depExpenseAccountCode || "5410",
    status: "active",
    lastDepreciatedThrough: null,
    totalDepreciated: 0,
    disposalDate: null,
    disposalAmount: null,
    disposalNotes: "",
    notes: payload.notes || "",
    createdAt: new Date().toISOString(),
    createdBy: userName || "",
  };
  const ref = await addDoc(collection(db, COLLECTION), docData);
  return { id: ref.id, ...docData };
}

/* ─── Update an existing asset.
   If acquisitionDate or usefulLifeMonths or convention changes, recompute
   the depreciation schedule. ─── */
export async function updateFixedAsset(id, patch, userName){
  const ref = doc(db, COLLECTION, id);
  const update = { ...patch };
  /* Recompute schedule if any of the inputs changed */
  if(patch.acquisitionDate || patch.usefulLifeMonths || patch.convention){
    const current = await getFixedAsset(id);
    if(current){
      const merged = { ...current, ...patch };
      const schedule = computeDepreciationSchedule(
        merged.acquisitionDate,
        merged.usefulLifeMonths,
        merged.convention
      );
      update.depreciationStartMonth = schedule.startMonth;
      update.depreciationEndMonth = schedule.endMonth;
    }
  }
  update.modifiedAt = new Date().toISOString();
  update.modifiedBy = userName || "";
  await updateDoc(ref, update);
}

/* ─── Delete an asset (only if no depreciation has been posted) ─── */
export async function deleteFixedAsset(id){
  const asset = await getFixedAsset(id);
  if(!asset) throw new Error("الأصل غير موجود");
  if(Number(asset.totalDepreciated) > 0){
    throw new Error("لا يمكن حذف أصل تم ترحيل إهلاك له. استخدم 'تصرف في الأصل' بدلاً من ذلك");
  }
  if(asset.status === "disposed"){
    throw new Error("الأصل تم التصرف فيه بالفعل — لا يمكن حذفه");
  }
  await deleteDoc(doc(db, COLLECTION, id));
}

/* ─── Mark as disposed (after the disposal journal entry posted successfully) ─── */
export async function markAssetDisposed(id, disposalInfo, userName){
  const ref = doc(db, COLLECTION, id);
  await updateDoc(ref, {
    status: "disposed",
    disposalDate: disposalInfo.disposalDate,
    disposalAmount: Number(disposalInfo.disposalAmount) || 0,
    disposalNotes: disposalInfo.disposalNotes || "",
    modifiedAt: new Date().toISOString(),
    modifiedBy: userName || "",
  });
}

/* ─── Update depreciation tracking after a depreciation entry is posted ─── */
export async function recordDepreciationProgress(id, throughMonth, addedAmount){
  const ref = doc(db, COLLECTION, id);
  /* Use transaction so concurrent runs don't lose totals */
  await runTransaction(db, async tx => {
    const snap = await tx.get(ref);
    if(!snap.exists()) return;
    const cur = snap.data();
    const newTotal = (Number(cur.totalDepreciated) || 0) + (Number(addedAmount) || 0);
    /* Mark as fully_depreciated if we've reached the end month */
    let status = cur.status || "active";
    if(status === "active" && cur.depreciationEndMonth && throughMonth >= cur.depreciationEndMonth){
      status = "fully_depreciated";
    }
    tx.update(ref, {
      lastDepreciatedThrough: throughMonth,
      totalDepreciated: newTotal,
      status,
    });
  });
}

/* ─── Helpers for UI/queries ─── */

/* Compute monthly depreciation amount (straight-line) */
export function monthlyDepreciation(asset){
  const cost = Number(asset.acquisitionCost) || 0;
  const salvage = Number(asset.salvageValue) || 0;
  const life = Number(asset.usefulLifeMonths) || 0;
  if(life <= 0) return 0;
  const depBase = cost - salvage;
  if(depBase <= 0) return 0;
  return Math.round((depBase / life) * 100) / 100;
}

/* Net book value = cost − accumulated depreciation */
export function bookValue(asset){
  const cost = Number(asset.acquisitionCost) || 0;
  const acc = Number(asset.totalDepreciated) || 0;
  return Math.round((cost - acc) * 100) / 100;
}

/* Asset category options (informational; users can type free text too) */
export const ASSET_CATEGORIES = [
  "ماكينات إنتاج",
  "أثاث ومفروشات",
  "كمبيوترات وأجهزة",
  "وسائل نقل",
  "تحسينات على المأجور",
  "أخرى",
];
